cobbler: Support CentOS Stream
ceph/ceph-cm-ansible pull request #621
Opened 2021-05-13 15:50 UTC by djgalloway

We have to do it this way for a number of reasons

1. The vmlinuz and initrd in the CentOS Stream ISO aren't compatible. https://bugs.centos.org/view.php?id=18188
2. The version of Cobbler we're running does not recognize CentOS Stream ISO without hacking the distro_signatures file
3. Probably most importantly, when using the CentOS Stream ISO, after the installation is finished, we bizarrely end up with CentOS 8.3...  Not Stream.

Signed-off-by: David Galloway <dgallowa@redhat.com>

2021-05-17 21:50 UTC, zmc requested changes
One comment that should be addressed. Also, a non-blocking suggestion:

I see you use `{% if 'Stream' in ansible_lsb.description %}-stream{% endif %}` in a _lot_ of places; would it make sense to use `set_fact` to set a variable to that value e.g. `stream_prefix` then simply use `{stream_prefix}` in the templates? Its value would either be `'-stream'` or `''`

2021-05-17 21:50 UTC, zmc commented on roles/cobbler_profile/tasks/import_stream_profile.yml
> +# See commit message for why we do it this way
Almost got me. There's no commit message with an explanation.

2021-05-17 22:26 UTC, djgalloway commented on roles/cobbler_profile/tasks/import_stream_profile.yml
> +# See commit message for why we do it this way
Oh sonofa

2021-05-17 22:27 UTC, djgalloway commented
> One comment that should be addressed. Also, a non-blocking suggestion:
> 
> I see you use `{% if 'Stream' in ansible_lsb.description %}-stream{% endif %}` in a _lot_ of places; would it make sense to use `set_fact` to set a variable to that value e.g. `stream_prefix` then simply use `{stream_prefix}` in the templates? Its value would either be `'-stream'` or `''`

Yep.  Good suggestion.  I will implement that!

2021-05-19 15:34 UTC, akraitman approved these changes

2021-05-19 15:58 UTC, merged